# Create a new directory for your project
mkdir trulens_chatbot
cd trulens_chatbot

# Create a virtual environment named "trulens_chatbot" with Python 3.10
conda create -n trulens_chatbot python=3.10

# Activate the virtual environment
conda activate trulens_chatbot

# Install the necessary libraries
pip install streamlit langchain trulens-eval openai
